# AWS CodeBuild Configuration
version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm i -g nx
      - npm install
  build:
    commands:
      # - echo testing...
      - echo building...
      - nx build --prod
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/apps/dcompas